left_camera:
  address: 192.168.1.180
  port: 7766
  topic: image_raw
  is_depth_img: false
right_camera:
  address: 192.168.1.180
  port: 7767
  topic: image_raw
  is_depth_img: false
depth_camera:
  address: 192.168.1.180
  port: 7768
  topic: image_raw
  is_depth_img: true
imu:
  address: 192.168.1.180
  port: 7774
  topic: data_raw
lidar:
  address: 192.168.1.180
  port: 7773
  topic: scan
att_controller:
  address: 192.168.1.23
  port: 7771
  topic: control_cmd
ground_truth:
  address: 192.168.1.180
  port: 7775
  topic: ground_truth_odom
