left_camera:
  address: 192.168.2.160
  port: 6766
  topic: image_raw
  is_depth_img: false
right_camera:
  address: 192.168.2.160
  port: 6767
  topic: image_raw
  is_depth_img: false
depth_camera:
  address: 192.168.2.160
  port: 6768
  topic: image_raw
  is_depth_img: true
imu:
  address: 192.168.2.160
  port: 6769
  topic: data_raw
lidar:
  address: 192.168.2.160
  port: 6770
  topic: scan